Support for custom consensus on private networks
algorand/indexer pull request #1041
Opened 2022-06-20 22:41 UTC by scholtz

## Summary

Algorand indexer at the moment does not allow using custom consensus on private networks. This pull request adds this feature.

## Test Plan

I tested it manually on custom made private network with custom consensus.

2022-06-20 22:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/algorand/indexer?pullRequest=1041) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/algorand/indexer?pullRequest=1041) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/algorand/indexer?pullRequest=1041) it.</sub>

2022-06-23 22:17 UTC, Eric-Warehime commented
Hi, I'm not sure if I can see what this would do since block data in the indexer is imported independent of the consensus process. Can you give me a bit of background on why you might need this change?

2022-06-24 10:41 UTC, scholtz commented
hi @Eric-Warehime 

sure, algod loads correctly custom consensus from consensus.json file.

but there is no way to use custom consensus with the indexer.. 

the indexer without this bugfix fails here https://github.com/algorand/indexer/blob/5be3c0e17e455b037a05c941b305a4378b420d55/importer/importer.go#L27 with error **protocol 'custom-protocol' not found**

if you want, you can find the way to load consensus from the algod server, but right now you are using hardcoded consensus values with no option to extend it.. this PR is simple fix to resolve the issue with ability to provide consensus.json file with the indexer

2022-07-01 16:39 UTC, Eric-Warehime requested changes
Looks good to me. Just need to fix the fmt issue

2022-07-04 19:07 UTC, Eric-Warehime requested changes

2022-07-04 19:07 UTC, Eric-Warehime commented on cmd/algorand-indexer/daemon.go
> +			}else{
```suggestion
			} else {
```

2022-11-13 14:38 UTC, closed without merging