Adds cpu profile and pid flag
algorand/indexer pull request #1209
Opened 2022-08-30 14:09 UTC by AlgoStephenAkiki

Resolves #1172

Adds the options for cpu profiling and pid flags as well as unit tests

## Summary

Explain the goal of this change and what problem it is solving. Format this cleanly so that it may be used for a commit message, as your changes will be squash-merged.

## Test Plan

How did you test these changes? Please provide the exact scenarios you tested in as much detail as possible including commands, output and rationale.

2022-08-30 15:58 UTC, shiqizng commented on conduit/pipeline.go
> +	if err != nil {
consider using
```suggestion
	if err:=fmt.Fprintf(fout, "%d", os.Getpid()); err != nil {
	}
```

2022-08-30 16:04 UTC, shiqizng approved these changes

2022-08-31 19:00 UTC, Eric-Warehime requested changes

2022-09-01 16:38 UTC, Eric-Warehime approved these changes

2022-09-01 18:01 UTC, merged

2022-09-02 01:04 UTC, winder commented on conduit/pipeline_test.go
> +		assert.Nil(t, err)
nit: assert.NoError(t, err)