Update indexer master (legacy) line for go 1.20.
algorand/indexer pull request #1549
Opened 2023-06-16 10:54 UTC by gmalouf

## Summary

Support go 1.20 on the master branch.

## Test Plan

* go mod tidy
* unit tests
* etc

2023-06-16 12:49 UTC, winder approved these changes

2023-06-16 17:15 UTC, Eric-Warehime approved these changes

2023-06-16 18:00 UTC, algobarb approved these changes

2023-06-20 17:06 UTC, algobarb requested changes
I think the Hyper-Flow team decided that we shouldn't merge changes directly into master branch and we should create either a separate hotfix or release branch for these changes to merge to first. @onetechnical

2023-06-21 15:56 UTC, algobarb commented
Can we rebase this PR to this hotfix branch: https://github.com/algorand/indexer/tree/hotfix/2.15.5

2023-06-21 16:00 UTC, gmalouf commented
I think this should just be targeted at master no?

On Wed, Jun 21, 2023 at 11:56 AM algobarb ***@***.***> wrote:

> Can we rebase this PR to this hotfix branch:
> https://github.com/algorand/indexer/tree/hotfix/2.15.5
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/algorand/indexer/pull/1549#issuecomment-1601103113>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHP3U4HICSWRGAWMYK7VADXMMKURANCNFSM6AAAAAAZJC26OQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-15 21:42 UTC, closed without merging