bug-fix: update module path and version
algorand/indexer pull request #1558
Opened 2023-07-06 20:02 UTC by shiqizng

This PR resolves the problem stated in #1557  

```
./algorand-indexer -v
2.15.2 compiled at 2023-07-06T19:04:37+0000 from git hash 61f0d133962bbec0a4bb680ead05f8e773a965f2 
```
curl "localhost:8980/health?pretty
```
{
    "data": {
        "migration-required": false,
        "read-only-mode": true
    },
    "db-available": true,
    "is-migrating": false,
    "message": "102",
    "round": 102,
    "version": "3.0.0"
}

```

2023-07-07 00:20 UTC, winder requested changes
* I don't think .version is used anymore, please delete it.
* The LDFLAGS are also defined in .goreleaser.yaml

2023-07-07 00:22 UTC, winder commented on Makefile
> +GOLDFLAGS += -X github.com/algorand/indexer/v3/version.ReleaseVersion=$(shell cat .version)
Something from Conduit to mark local builds differently
```suggestion
GOLDFLAGS += -X "github.com/algorand/indexer/v3/version.ReleaseVersion=Dev Build"
```

2023-07-07 16:54 UTC, Eric-Warehime approved these changes

2023-07-11 13:29 UTC, winder approved these changes

2023-07-11 13:29 UTC, merged