added network check
algorand/indexer pull request #833
Opened 2022-01-24 15:15 UTC by shiqizng

## Summary
Write and check networkID during startup. 

## Test Plan
Add a test to postgres_integration_test

2022-01-24 20:31 UTC, tolikzinovyev reviewed
Is network ID enough? There might be some other parameters. Why not use the genesis hash?

2022-01-24 20:31 UTC, tolikzinovyev commented on idb/postgres/postgres.go
> +		network, err := db.getMetastate(context.Background(), nil, schema.NetworkMetaStateKey)
suggest making `getNetworkState()` and `setNetworkState()` similar to `?etImportState()` and `?etMigrationState()`.

2022-01-24 20:31 UTC, tolikzinovyev commented on idb/postgres/postgres.go
> +				return fmt.Errorf("LoadGenesis() err: NetworkID does not match")
Styling: "err: " means `err` is a variable. Just write `return fmt.Errorf("LoadGenesis() NetworkID does not match")`.

2022-01-24 20:31 UTC, tolikzinovyev commented on idb/postgres/postgres_integration_test.go
> +
empty line

2022-01-24 20:50 UTC, shiqizng commented
> Is network ID enough? There might be some other parameters. Why not use the genesis hash?

genesis hash isn't in bookkeeping.Genesis struct and so the hash is not available in LoadGenesis(genesis bookkeeping.Genesis).

2022-01-24 21:01 UTC, tolikzinovyev commented
> > Is network ID enough? There might be some other parameters. Why not use the genesis hash?
> 
> genesis hash isn't in bookkeeping.Genesis struct and so the hash is not available in LoadGenesis(genesis bookkeeping.Genesis). Maybe it's better to use Genesis.ID()?
> 
> ```
> // ID is the effective Genesis identifier - the combination
> // of the network and the ledger schema version
> func (genesis Genesis) ID() string {
> 	return string(genesis.Network) + "-" + genesis.SchemaID
> }
> ```

Seems like there is infrastructure for hashing `bookkeeping.Genesis`. https://github.com/algorand/go-algorand/blob/master/data/bookkeeping/genesis.go#L121 I just don't know how to invoke it.

2022-01-25 16:45 UTC, shiqizng commented
> > > Is network ID enough? There might be some other parameters. Why not use the genesis hash?
> > 
> > 
> > genesis hash isn't in bookkeeping.Genesis struct and so the hash is not available in LoadGenesis(genesis bookkeeping.Genesis). Maybe it's better to use Genesis.ID()?
> > ```
> > // ID is the effective Genesis identifier - the combination
> > // of the network and the ledger schema version
> > func (genesis Genesis) ID() string {
> > 	return string(genesis.Network) + "-" + genesis.SchemaID
> > }
> > ```
> 
> Seems like there is infrastructure for hashing `bookkeeping.Genesis`. https://github.com/algorand/go-algorand/blob/master/data/bookkeeping/genesis.go#L121 I just don't know how to invoke it.

I changed the check to use genesis hash. I removed network ID check since the hash includes the ID also.

2022-01-25 17:13 UTC, tolikzinovyev requested changes

2022-01-25 17:13 UTC, tolikzinovyev commented on idb/postgres/internal/encoding/encoding_test.go
> +	"github.com/algorand/indexer/idb/postgres/internal/types"
this should move below

2022-01-25 17:13 UTC, tolikzinovyev commented on idb/postgres/postgres.go
> +		network, err := db.getNetworkState(context.Background(), nil)
this should use `tx`

2022-01-25 17:13 UTC, tolikzinovyev commented on idb/postgres/postgres.go
> +			err = db.setNetworkState(nil, &networkState)
this should use `tx`

2022-01-25 18:13 UTC, tolikzinovyev approved these changes
LGTM

2022-01-25 18:51 UTC, merged